about/urls.py
from django.urls import path
from about import views
app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
]

contacts/urls.py
from django.urls import path
from contacts import views

app_name = 'contacts'

urlpatterns = [
    path('', views.contact, name='contact'),
    ]

gallerys/urls.py
from django.urls import path
from gallerys import views

app_name = 'gallerys'

urlpatterns = [
    path('catalog/<slug:category_slug>/', views.catalog, name='catalog'),
    path('photo/<slug:photoshoot_slug>/', views.photo, name='photo'),
    path('genre/', views.genre, name='genre'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

photographer_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf.urls.static import static

from photographer_site import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('gallerys/', include('gallerys.urls'), name='gallerys'),
    path('services/', include('services.urls'), name='services'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('about/', include('about.urls'), name='about'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from services import views

app_name = 'services'

urlpatterns = [
    path('', views.index, name='index'),
    path('shooting_type/<slug:category_slug>/', views.shooting_type, name='shooting_type'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mari Mazi</title>

    <link rel="stylesheet" href="{% static 'deps/css/footer.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/navigator.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/scroll_top.css' %}"> <!-- Подключение стилевого файла -->
    {% block css %}

    {% endblock %}
    <link rel="icon" type="image/jpg" sizes="16x16" href="{% static 'deps/icons/title.jpg' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>

{% block before %}

{% endblock %}

<header class="header-nav">  <!-- Новый класс для навигации -->
        <nav>
            <ul class="navigation-menu">
                <li><a href="{% if is_home %}#home {% else %}{% url 'main:index' %}{% endif %}">Главная</a></li>
                <li><a href="{% url 'about:about' %}">Обо мне</a></li>
                <li><a href="{% if is_home %}#gallery {% else %}{% url 'gallerys:genre' %}{% endif %}">Галерея</a></li>
                <li><a href="{% if is_home %}#services {% else %}{% url 'services:index' %}{% endif %}">Услуги</a></li>
                <li><a href="{% if is_home %}#contacts {% else %}{% url 'contacts:contact' %}{% endif %}">Контакты</a></li>
            </ul>
        </nav>
</header>

{% block content %}

{% endblock %}

<!-- Футер с контактной информацией и ссылками на социальные сети -->
    <footer>
        <div class="social-media">
            <a href="https://instagram.com">Instagram</a>
            <a href="https://facebook.com">Facebook</a>
        </div>
        <p>Контакты: mary.mazi@mail.com | +7 (988) 954-68-74</p>
        <p>&copy; 2024 Фотограф Мария. Все права защищены.</p>
    </footer>

<a href="#" class="scroll-to-top" id="scrollToTopBtn">↑</a>

<script src="{% static 'deps/js/scripts_navigator.js' %}"></script>

</body>
</html>