gallerys/urls.py
from django.urls import path
from gallerys import views

app_name = 'gallerys'

urlpatterns = [
    path('catalog/<slug:category_slug>/', views.catalog, name='catalog'),
    path('photo/<slug:photoshoot_slug>/', views.photo, name='photo'),
    path('genre/', views.genre, name='genre'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

photographer_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf.urls.static import static

from photographer_site import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('gallerys/', include('gallerys.urls'), name='gallerys'),
    path('services/', include('services.urls'), name='services'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('about/', include('about.urls'), name='about'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from services import views

app_name = 'services'

urlpatterns = [
    path('', views.index, name='index'),
    path('shooting_type/<slug:category_slug>/', views.shooting_type, name='shooting_type'),
]

contacts/forms.py
from django import forms
from contacts.models import Client


class ContactForms(forms.ModelForm):
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(max_length=20, required=True)

    class Meta:
        model = Client
        fields = ('name', 'email', 'phone',)

main/views.py
from django.shortcuts import render, redirect
from contacts.models import Client
from contacts.forms import ContactForms
from django.http import HttpResponse
from django.contrib import messages
from django.core.mail import send_mail



def index(request):
    if request.method == 'POST':
        form = ContactForms(data=request.POST)
        if form.is_valid():
            name = request.POST['name']
            email = request.POST['email']
            phone = request.POST['phone']
            form.save()
            messages.success(request, f'заявка подана, я свяжусь с вами в скором времени')
    else:
        form = ContactForms()

    context = {
        'title': 'Фотограф Meri Mazi',
        'content_1': 'Фотограф',
        'content_2': 'Meri Mazi',
        'form': form,
        'is_home': True,
    }
    return render(request, 'main/index.html', context)

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/styles.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/about_me.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/gallery.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/services.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/contact.css' %}"> <!-- Подключение стилевого файла -->
{% endblock %}


{% block before %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div id="notification" class="alert alert-success fade show custom-shadow" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

    <!-- Заголовок сайта -->
    <div class="logo">
        <h1>
            <span class="highlight">{{content_1}}</span><br>
            <span class="highlight subtitle">{{content_2}}</span>
        </h1>
    </div>
{% endblock %}



{% block content %}
    <!-- Секция hero с основным изображением -->
    <section id='home' class="hero" style="background-image: url('{% static 'deps/images/main_photo.jpg' %}');">
    <div class="hero-overlay"></div>
    <div class="hero-text">
        <h2>Запечатлите самые важные моменты</h2>
        <a href="#about" class="btn">Подробней</a> <!-- Добавлена кнопка -->
    </div>
</section>

    <!-- Обо мне -->
    <section id="about" class="about-section" style=" background-image: url('{% static 'deps/images/about_photo3.jpg' %}');">
        <div class="about-overlay"></div>
        <h2>Обо мне</h2>
        <p> Я – профессиональный фотограф с опытом работы более 10 лет. Мой стиль – это искусство запечатлевать мгновения, создавая уникальные истории через объектив. </p>
</section>

    <!-- Галерея работ -->
    <section id="gallery">
    <h2>Галерея работ</h2>
    <div class="gallery-grid">
        <a href="{% url 'gallerys:photo' 'paparacii' %}" class="gallery-item">
            <img src="{% static 'deps/images/list_photo/photo_4.jpg' %}" alt="Работа 1">
            <div class="overlay">
                <span>Смотреть работы</span>
            </div>
        </a>
        <a href="{% url 'gallerys:photo' 'bardovoe-pyatno' %}" class="gallery-item">
            <img src="{% static 'deps/images/list_photo/photo_2.jpg' %}" alt="Работа 2">
            <div class="overlay">
                <span>Смотреть работы</span>
            </div>
        </a>
        <a href="{% url 'gallerys:photo' 'strogost' %}" class="gallery-item">
            <img src="{% static 'deps/images/list_photo/photo_3.jpg' %}" alt="Работа 3">
            <div class="overlay">
                <span>Смотреть работы</span>
            </div>
        </a>
        <a href="{% url 'gallerys:photo' 'temnyj-stil' %}" class="gallery-item">
            <img src="{% static 'deps/images/list_photo/photo_5.jpg' %}" alt="Работа 4">
            <div class="overlay">
                <span>Смотреть работы</span>
            </div>
        </a>
        <a href="{% url 'gallerys:photo' 'nezhnost' %}" class="gallery-item">
            <img src="{% static 'deps/images/list_photo/photo_6.jpg' %}" alt="Работа 5">
            <div class="overlay">
                <span>Смотреть работы</span>
            </div>
        </a>
        <a href="{% url 'gallerys:photo' 'krasnaya-blondinka' %}" class="gallery-item">
            <img src="{% static 'deps/images/list_photo/photo_7.jpg' %}" alt="Работа 6">
            <div class="overlay">
                <span>Смотреть работы</span>
            </div>
        </a>
    </div>
    <a href="{% url 'gallerys:genre' %}" class="show-more">Показать еще работы</a>
</section>



    <!-- Услуги, предлагаемые фотографом -->
    <section id="services">
    <h2>Услуги</h2>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'portretnaya-semka' %}">
            <img src="{% static 'deps/images/services/portrait.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Портретная съемка</h3>
            <p>Краткое описание портретной съемки. Мы предлагаем профессиональные услуги по созданию портретов в различных стилях.</p>
            <a href="{% url 'services:shooting_type' 'portretnaya-semka' %}" class="btn2">Смотреть</a>
        </div>
    </div>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'feshn-semka' %}">
            <img src="{% static 'deps/images/services/fashion.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Фешн съемка</h3>
            <p>Краткое описание фешн съемки. Стильные фотографии, которые помогут выделить вашу индивидуальность.</p>
            <a href="{% url 'services:shooting_type' 'feshn-semka' %}" class="btn2">Смотреть</a>
        </div>
    </div>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'byuti-semka' %}">
            <img src="{% static 'deps/images/services/beauty.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Бьюти съемка</h3>
            <p>Краткое описание бьюти съемки. Профессиональные фотосессии для журналов и социальных сетей.</p>
            <a href="{% url 'services:shooting_type' 'byuti-semka' %}" class="btn2">Смотреть</a>
        </div>
    </div>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'studijnaya-fotografiya' %}">
            <img src="{% static 'deps/images/services/stud.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Студийная фотография</h3>
            <p>Краткое описание студийной фотографии. Лучшие условия и оборудование для качественной съемки.</p>
            <a href="{% url 'services:shooting_type' 'studijnaya-fotografiya' %}" class="btn2">Смотреть</a>
        </div>
    </div>
</section>

 <!-- Секция "Контакты" -->
<section id="contacts">
    <h2>Контакты</h2>
    <div class="contact-container">
        <!-- Левая сторона: форма для заполнения -->
        <div class="contact-form">
            <p class="form-intro">Оставьте заявку на съемку, и я свяжусь с вами</p>
            <form action="{% url 'main:index' %}" method="POST">
                        {% csrf_token %}
                <label for="id_name">Имя:</label>
                <input type="text" id="id_name"
                       value="{% if form.name.value %} {{form.name.value}}{% endif %}"
                       name="name"
                       placeholder="Введите ваше имя" required>
                {% if form.name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.name.errors}}</div>
                {% endif %}

                <label for="id_email">Email:</label>
                <input type="email" id="id_email"
                       value="{% if form.email.value %} {{form.email.value}}{% endif %}"
                       name="email"
                       placeholder="Введите ваш email" required>
                {% if form.name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                {% endif %}

                <label for="id_phone">Номер телефона:</label>
                <input type="tel" id="id_phone"
                       value="{% if form.phone.value %} {{form.phone.value}}{% endif %}"
                       name="phone"
                       placeholder="Введите ваш номер телефона" required>
                {% if form.phone.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.phone.errors}}</div>
                {% endif %}

                <button type="submit" class="submit-button">Отправить</button>
                <p class="privacy-notice">Нажимая кнопку "Отправить", вы соглашаетесь с политикой конфиденциальности.</p>
            </form>
        </div>

        <!-- Правая сторона: информация и кнопки -->
        <div class="contact-info">
            <h3>Связаться со мной</h3>
            <p>Email: <a href="mailto:mary.mazy@mail.com" class="email-link">mary.mazy@mail.com</a></p>
            <p>Телефон: <span class="phone-number">+7 (988) 954-68-74</span></p>
            <div class="social-buttons">
                <a href="https://t.me/Zhenya1Kot" class="social-button telegram">Написать мне в Телеграмм</a>
                <a href="https://wa.me/+79628531872" class="social-button whatsapp">Написать мне в Ватсапп</a>
                <a href="https://vk.com/kotssccc" class="social-button vk">Написать мне в ВКонтакте</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}