contacts/urls.py
from django.urls import path
from contacts import views

app_name = 'contacts'

urlpatterns = [
    path('', views.contact, name='contact'),
    ]

gallerys/urls.py
from django.urls import path
from gallerys import views

app_name = 'gallerys'

urlpatterns = [
    path('catalog/<slug:category_slug>/', views.catalog, name='catalog'),
    path('photo/<slug:photoshoot_slug>/', views.photo, name='photo'),
    path('genre/', views.genre, name='genre'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

photographer_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf.urls.static import static

from photographer_site import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('gallerys/', include('gallerys.urls'), name='gallerys'),
    path('services/', include('services.urls'), name='services'),
    path('contacts/', include('contacts.urls'), name='contacts'),
    path('about/', include('about.urls'), name='about'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from services import views

app_name = 'services'

urlpatterns = [
    path('', views.index, name='index'),
    path('shooting_type/<slug:category_slug>/', views.shooting_type, name='shooting_type'),
]

services/views.py
from django.shortcuts import render, get_object_or_404

from gallerys.models import Photoshoot, Photo, Categories


def index(request):
    return render(request, 'services/services_index.html')


def shooting_type(request, category_slug):
    category = get_object_or_404(Categories, slug=category_slug)
    photoshoots = Photoshoot.objects.filter(category=category)
    first_photos = []
    for photoshoot in photoshoots:
        first_photo = photoshoot.photos.first()
        if first_photo:
            if len(first_photos) < 3:
                first_photos.append(first_photo)
            else:
                break

    context = {
        'photoshoots': photoshoots,
        'first_photos': first_photos,
        'category': category,
    }
    return render(request, 'services/services_category.html', context)

services/templates/services/services_category.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/category_services.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/uslug.css' %}"> <!-- Подключение стилевого файла -->
{% endblock %}


{% block before %}
<section id='home_catalog' class="hero" style="background-image: url('{% static 'deps/images/photoshoot_type.jpg' %}');">
    <div class="hero-overlay"></div>
    <div class="hero-text">
        <h1>Прайс и услуги </h1>
    </div>
</section>
{% endblock %}


{% block content %}
<section class="photography-service">
    <div class="container">
        <h1 class="centered-title">{{ category }}</h1>

        <div class="service-content">
            <div class="services-list">
                <h2 class="service-title">Что входит в фотосессию:</h2>
                <ul class="service-list">
                    <li><strong>Время:</strong> 2 часа съемки</li>
                    <li><strong>Итоговое количество фото:</strong> 50 снимков</li>
                    <li><strong>Обработанные фото:</strong> 15 отобранных и обработанных изображений</li>
                    <li><strong>Консультация:</strong> Помощь в выборе стиля и образов</li>
                    <li><strong>Бронирование студии:</strong> Включено в стоимость</li>
                    <li><strong>Срок готовности:</strong> 1 неделя</li>
                    <li><strong>Разнообразные фоны:</strong> Выбор из 5 различных фонов</li>
                    <li><strong>Профессиональный осветитель:</strong> Включен в стоимость</li>
                    <li><strong>Препарация образов:</strong> Подготовка перед съемкой</li>
                </ul>
                <h2 class="price-title">Стоимость фотосессии:</h2>
                <p class="price">Цена: <strong>5000 руб.</strong></p>
            </div>

            <div class="stylist-services">
                <h2 class="service-title">Услуги стилиста:</h2>
                <ul class="service-list">
                    <li>Подбор образов</li>
                    <li>Макияж и прическа</li>
                    <li>Консультационные услуги</li>
                </ul>
                <p class="stylist-price"></p>
                <h2 class="price-title">Стоимость фотосессии с услугами стилиста:</h2>
                <p class="price">Цена: <strong>8000 руб.</strong></p>
            </div>
        </div>

        <div class="button-container">
            <a href="{% url 'contacts:contact' %}">
            <button class="btn-book">Забронировать</button>
            </a>
        </div>

<div class="portfolio-preview">
    <h2>Посмотрите мои работы из этой категории:</h2>
    <div class="portfolio-images">
        {% for photo in first_photos %}
        <a href="{% url 'gallerys:photo' photo.photoshoot.slug %}">
            <img src="{{ photo.image.url }}" alt="{{ forloop.counter }}">
        </a>
        {% endfor %}
    </div>
    <div class="button-container">
        <a href="{% url 'gallerys:catalog' category.slug %}">
        <button class="btn-view-all">Смотреть все работы</button>
        </a>
    </div>
</div>

    </div>
</section>
{% endblock %}

services/templates/services/services_index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/services.css' %}"> <!-- Подключение стилевого файла -->
    <link rel="stylesheet" href="{% static 'deps/css/uslug.css' %}"> <!-- Подключение стилевого файла -->
{% endblock %}


{% block before %}
<section id='home_catalog' class="hero" style="background-image: url('{% static 'deps/images/services_main.jpg' %}');">>
    <div class="hero-overlay"></div>
    <div class="hero-text">
        <h1>Я предоставляю несколько категорий съемок и услуг </h1>
    </div>
</section>
{% endblock %}


{% block content %}
   <!-- Услуги, предлагаемые фотографом -->
    <section id="services">
    <h2>Услуги</h2>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'portretnaya-semka' %}">
            <img src="{% static 'deps/images/services/portrait.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Портретная съемка</h3>
            <p>Краткое описание портретной съемки. Мы предлагаем профессиональные услуги по созданию портретов в различных стилях.</p>
            <a href="{% url 'services:shooting_type' 'portretnaya-semka' %}" class="btn2">Смотреть</a>
        </div>
    </div>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'feshn-semka' %}">
            <img src="{% static 'deps/images/services/fashion.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Фешн съемка</h3>
            <p>Краткое описание фешн съемки. Стильные фотографии, которые помогут выделить вашу индивидуальность.</p>
            <a href="{% url 'services:shooting_type' 'feshn-semka' %}" class="btn2">Смотреть</a>
        </div>
    </div>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'byuti-semka' %}">
            <img src="{% static 'deps/images/services/beauty.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Бьюти съемка</h3>
            <p>Краткое описание бьюти съемки. Профессиональные фотосессии для журналов и социальных сетей.</p>
            <a href="{% url 'services:shooting_type' 'byuti-semka' %}" class="btn2">Смотреть</a>
        </div>
    </div>

    <div class="service-item">
        <a href="{% url 'services:shooting_type' 'studijnaya-fotografiya' %}">
            <img src="{% static 'deps/images/services/stud.jpg' %}" class="service-image">
        </a>
        <div class="service-description">
            <h3>Студийная фотография</h3>
            <p>Краткое описание студийной фотографии. Лучшие условия и оборудование для качественной съемки.</p>
            <a href="{% url 'services:shooting_type' 'studijnaya-fotografiya' %}" class="btn2">Смотреть</a>
        </div>
    </div>
</section>
{% endblock %}